Models/UsersModels/UserAdministrator.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SEP_Web.Models.UsersModels;

/// <summary>
///     <para><b>Administradores:</b></para>
///     <para>- Os administradores herdam seus atributos da classe base <b>SEP_Web.Models.Users</b>.
///     Eles possuem todas as permissões de acesso e modificação sobre os subníveis de usuários
///     e demais estruturas acessíveis do sistema.</para>
///     <para>- A classe <b>UserAdministrator</b> é usada para mapear uma tabela do banco de dados,
///     representando uma entidade gerada pelo <b>EF Core</b>.</para>
///     <para><b>Nome da Tabela:</b></para>
///     <para>- Administrators;</para>
/// </summary>

[Table("Administrators")]
public class UserAdministrator : Users
{

}

Controllers/Users/UserAdministratorController.cs
using Microsoft.AspNetCore.Mvc;
using MySqlConnector;
using SEP_Web.Filters;
using SEP_Web.Helper.Authentication;
using SEP_Web.Helper.Messages;
using SEP_Web.Helper.Validation;
using SEP_Web.Keys;
using SEP_Web.Models;
using SEP_Web.Models.UsersModels;
using SEP_Web.Interfaces.UsersInterfaces;
using SEP_Web.Models.DataTableModels;
using SEP_Web.ViewModels;

namespace SEP_Web.Controllers.UsersControllers;

[ServiceFilter(typeof(UserAdminFilter))]
public class UserAdministratorController : Controller
{
    private readonly ILogger<UserAdministratorController> _logger;
    private readonly IUserAdministratorServices _administratorServices;
    private readonly IUsersValidation _validation;
    private readonly IUserSession _session;


    public UserAdministratorController(ILogger<UserAdministratorController> logger, IUserAdministratorServices administratorServices, IUsersValidation validation, IUserSession session)
    {
        _logger = logger;
        _administratorServices = administratorServices;
        _validation = validation;
        _session = session;
    }
    public IActionResult Index() => View();

    [HttpPost]
    public IActionResult Index(DataTableRequest request)
    {
        try
        {
            // Obter IQueryable<UserAdministrator> do serviço
            var query = _administratorServices.AdministratorsAsQueryable();

            // Converter IQueryable<UserAdministrator> para IQueryable<UsersViewModel>
            var viewModels = ConvertToViewModel(query);

            // Aplicando a ordenação
            if (request.Order != null && request.Order.Any())
            {
                var columnIndex = request.Order[0].Column; // Índice da coluna que está sendo ordenada
                var sortDirection = request.Order[0].Dir; // Direção da ordenação: "asc" ou "desc"

                switch (columnIndex)
                {
                    case 0:
                        viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.UserStats).AsQueryable()  // Ajustar para a coluna correta
                            : viewModels.OrderByDescending(u => u.UserStats).AsQueryable();
                        break;
                    case 1:
                         viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.Masp).AsQueryable()
                            : viewModels.OrderByDescending(u => u.Masp).AsQueryable();
                        break;
                    case 2:
                        viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.Name).AsQueryable()
                            : viewModels.OrderByDescending(u => u.Name).AsQueryable();
                        break;
                    case 3:
                        viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.Login).AsQueryable()
                            : viewModels.OrderByDescending(u => u.Login).AsQueryable();
                        break;
                    case 4:
                        viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.Email).AsQueryable()
                            : viewModels.OrderByDescending(u => u.Email).AsQueryable();
                        break;
                    case 5:
                        viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.Phone).AsQueryable()
                            : viewModels.OrderByDescending(u => u.Phone).AsQueryable();
                        break;
                    default:
                        break;
                }
            }

            // Filtragem para busca via search
            if (!string.IsNullOrEmpty(request.Search.Value))
            {
                string searchValue = request.Search.Value.ToLower();
                viewModels = viewModels.Where(vm =>
                    vm.Name.ToLower().Contains(searchValue) ||
                    vm.Login.ToLower().Contains(searchValue) ||
                    vm.Email.ToLower().Contains(searchValue) ||
                    vm.Phone.ToLower().Contains(searchValue)
                ).AsQueryable();
            }

            // Filtragem, paginação e ordenação pelo DataTables
            var filteredData = viewModels.Skip(request.Start).Take(request.Length).ToList();
            var response = new
            {
                draw = request.Draw,
                recordsTotal = viewModels.Count(),
                recordsFiltered = viewModels.Count(),
                data = filteredData
            };

            return Json(response);
        }
        catch (MySqlException dbException)
        {
            // MYSQL EXEPTIONS :

            _logger.LogError("{exceptionMessage} : {Message}, ErrorCode = {errorCode} - Represents {Error} ", ExceptionMessages.ErrorDatabaseConnection, dbException.Message.ToUpper(), dbException.Number, dbException.ErrorCode);
            return new JsonResult(new
            {
                draw = 0,
                recordsTotal = 0,
                recordsFiltered = 0,
                data = new List<UsersViewModel>()
            });
        }
        catch (ArgumentNullException ex)
        {
            // NULL EXEPTIONS :

            _logger.LogWarning("{exceptionMessage} : {Message} value = '{InnerExeption}'", FeedbackMessages.ErrorEmptyCollection, ex.Message, ex.InnerException);
            return new JsonResult(new
            {
                draw = 0,
                recordsTotal = 0,
                recordsFiltered = 0,
                data = new List<UsersViewModel>()
            });
        }
    }

    public IActionResult Register() => View();

    [HttpPost]
    public async Task<IActionResult> Register(UserAdministrator user, string confirmPass)
    {
        try
        {

            if (string.IsNullOrEmpty(confirmPass))
            {
                TempData["ErrorPass"] = FeedbackMessages.ConfirmPassword;
                return View(user);
            }

            if (ModelState.IsValid)
            {
                List<(string FieldName, string Message)> duplicateErrors = await _validation.CheckForDuplicateUserFields(user);

                foreach (var (FieldName, Message) in duplicateErrors)
                    ModelState.AddModelError(FieldName, Message);

                if (ModelState.ErrorCount > 0)
                    return View(user);

                if (!_validation.ValidatePassword(user.Password, confirmPass, this))
                    return View(user);

                /* Assim que todos os dados forem validados de acordo com as exigências; */

                TempData["SuccessMessage"] = FeedbackMessages.SuccessAdministratorRegister;

                await _administratorServices.RegisterAdministrator(user);
                return RedirectToAction("Index");
            }

            TempData.Clear();
            return View(user);
        }
        catch (MySqlException dbException)
        {
            // MYSQL EXEPTIONS :

            TempData["ErrorMessage"] = $"{FeedbackMessages.ErrorAdministratorRegister} {ExceptionMessages.ErrorDatabaseConnection}";

            _logger.LogError("[ADMINISTRATOR_CONTROLLER]: {exceptionMessage} : , {Message}, ErrorCode = {errorCode} - Represents {Error} ", ExceptionMessages.ErrorDatabaseConnection, dbException.Message.ToUpper(), dbException.Number, dbException.ErrorCode);

            _logger.LogError("[ADMINISTRATOR_CONTROLLER] : Detalhamento dos erros: {Description} - ", dbException.StackTrace.Trim());

            user = null;
            return View(user);
        }
        catch (ArgumentNullException nullException)
        {
            // NULL EXEPTIONS :

            TempData["ErrorMessage"] = FeedbackMessages.ErrorAdministratorRegister + " : " + FeedbackMessages.ErrorEmptyCollection; // Mensagem de vizualização para o usuário;

            _logger.LogWarning("[ADMINISTRATOR_CONTROLLER]: {exceptionMessage} : {Message}, Attribute = {ParamName}, value = '{InnerExeption}'", ExceptionMessages.ErrorArgumentNullException, nullException.Message, nullException.ParamName, nullException.InnerException);

            _logger.LogWarning("[ADMINISTRATOR_CONTROLLER]: {Description}", nullException.StackTrace.Trim());

            user = null;
            return View(user);
        }
    }

    public IActionResult Edit(int id) => View(_administratorServices.SearchForId(id));

    [HttpPost]
    public async Task<IActionResult> Edit(ModifyUser modifyUser)
    {
        try
        {
            UserAdministrator userEdit = _administratorServices.SearchForId(modifyUser.Id);

            if (ModelState.IsValid)
            {
                Users userInSession = await _session.SearchUserSession();

                bool enableAccount = Request.Form["enableDisableAccount"] == "on";

                if (enableAccount)
                {
                    userEdit.UserStats = userEdit.UserStats == UserStatsEnum.Active ? UserStatsEnum.Inactive : UserStatsEnum.Active;
                }

                if (enableAccount == true && userInSession.Masp == modifyUser.Masp)
                {
                    TempData["ErrorMessage"] = "Você desabilitou sua conta. Não será possível realizar login novamente com as suas credenciais. Entre em contato com um administrador!";

                    _session.UserCheckOut();
                }

                var fieldsToValidate = new List<(string FieldName, object Value)>
                {
                    ("Masp", modifyUser.Masp),
                    ("Name", modifyUser.Name),
                    ("Login", modifyUser.Login),

Views/UserAdministrator/Edit.cshtml
@model UserAdministrator

@using SEP_Web.Models
@using SEP_Web.Models.UsersModels
@using SEP_Web.Models.PasswordModels
@using SEP_Web.Keys

@{

    ViewData["Title"] = "Edição de administrador";
}

<div class="container">

    <div class="change-pass users-manager-container">

        <ul class="navbar-nav ml-auto">

            <li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle rounded-3 bg-primary text-light" id="menu-config"
                    title="Menu de modificações do usuário" role="button" data-bs-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false"><i class="bi bi-gear-fill"></i></a>

                <ul class="dropdown-menu" aria-labelledby="menu-config">
                    <li><a type="button" data-bs-toggle="modal" data-bs-target="#adm-change-pass"
                            title="Alterar senha do usuário !" class="dropdown-item"><i
                                title="Altere a senha do usuário !" class="bi bi-file-earmark-lock2"> </i>Alterar
                            senha</a>
                    </li>
                </ul>

            </li>

        </ul>

    </div>

    <div class="row justify-content-center">

        <div class="col-md-8 p-0 m-0">

            <div class="d-flex justify-content-center align-items-center">
                <div class="adm-line"></div>
                <i style="font-size: 10vh; color: #0077cc;" class="bi bi-person-lines-fill"></i>
                <div class="adm-line"></div>
            </div>

            <form class="register-adm-form" asp-controller="UserAdministrator" asp-action="Edit" method="post">

                <div class="pop-up-sm">
                    @await Html.PartialAsync("../Shared/Components/Alerts/_Alerts.cshtml")
                </div>

                <div class="row">

                    <div class="col-md-6 adm-col">

                        <div class="form-group mt-0  mb-0">

                            <label class="form-label" for="edit-administrator-masp" hidden></label>
                            <input type="number" class="form-control userMasp" id="edit-administrator-masp" name="masp"
                                asp-for="Masp" placeholder="Nº do MASP" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Masp)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="edit-administrator-name" hidden></label>
                            <input type="text" class="form-control" id="edit-administrator-name" name="Name"
                                asp-for="Name" placeholder="Nome completo" maxlength="50" minlength="10"
                                autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Name)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="edit-administrator-login" hidden></label>
                            <input type="text" class="form-control" id="edit-administrator-login" name="login"
                                asp-for="Login" placeholder="Nome de login" maxlength="35" minlength="10"
                                autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Login)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="edit-administrator-email" hidden></label>
                            <input type="text" class="form-control" id="edit-administrator-email" name="email"
                                asp-for="Email" placeholder="Informe seu e-mail" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Email)
                            </div>

                        </div>

                    </div>

                    <div class="col-md-6 adm-col">

                        <div class="form-group mt-0 mb-0">

                            <label class="form-label" for="edit-administrator-phone" hidden></label>
                            <input type="tel" class="form-control mask-phone" id="edit-administrator-phone" name="phone"
                                asp-for="Phone" maxlength="15" placeholder="(XX) XXXXX-XXXX" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Phone)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="edit-administrator-position" hidden></label>
                            <input type="text" class="form-control" id="edit-administrator-position" name="Position"
                                asp-for="Position" placeholder="Seu cargo" maxlength="35" minlength="10"
                                autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Position)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="edit-administrator-password" hidden></label>
                            <input type="password" class="form-control disabled-box" id="edit-administrator-password"
                                placeholder="Informe uma senha..."
                                title="Para alterar a senha utilize o menu 'Alterar senha'." disabled>
                            <div class="validate-fields"></div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="edit-administrator-confirmPass" hidden></label>
                            <input type="password" class="form-control disabled-box" id="edit-administrator-confirmPass"
                                placeholder="Confirme sua senha..."
                                title="Para alterar a senha utilize o menu 'Alterar senha'." disabled>
                            <div class="validate-fields"></div>

                        </div>

                    </div>

                </div>

                <div class="form-group d-flex flex-row justify-content-between">

                    <div class="mt-0">

                        <button title="Salve as alterações ..." type="submit" class="btn btn-primary"><i
                                class="bi bi-person-add" title="Salve as alterações ..."></i> Salvar</button>
                        <a href="/UserAdministrator/Index/" type="submit" class="btn btn-secondary"
                            title="Cancelar edição ..."><i class="bi bi-arrow-return-left"
                                title="Cancelar edição ..."></i></a>

                    </div>

                    <div class="btn-enableDisable">
                        @if (Model.UserStats == UserStatsEnum.Active)
                        {
                            <input class="form-check-input enableDisableAccount" id="disable-account" type="checkbox"
                                name="enableDisableAccount">
                            <label class="form-check-label ms-1" for="disable-account">Desabilitar usuário</label>
                        }
                        else
                        {
                            <input class="form-check-input enableDisableAccount" id="enable-account" type="checkbox"
                                name="enableDisableAccount">
                            <label class="form-check-label ms-1" for="enable-account">Habilitar usuário</label>
                        }
                    </div>

                </div>

            </form>

        </div>

    </div>

</div>

@* Start enable/disable user Modal *@

<div class="modal fade confirmationModal" id="confirmationModal" tabindex="-1" role="dialog"
    aria-labelledby="confirmationModalLabel" aria-hidden="true">

    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">

        <div class="modal-content">

            <div class="modal-header bg-danger p-3">
                <h3 class="modal-title text-light text-center fs-4 mb-0 p-0" id="confirmationModalLabel">
                    Alerta</h3>
                <button type="button" title="Fechar modal" id="modal-close" class="btn-close bg-light text-light"
                    data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>

            @if (Model.UserStats == UserStatsEnum.Active)
            {

                <div class="modal-body enableDisableModal p-3">
                    <span class="text-danger fw-bold">Atenção!</span> desabilitar o usuário fará com que ele perca o <span
                        class="fw-bold">completo acesso ao sistema</span>. Ao prosseguir você concorda em <span
                        class="fw-bold">desabilitar</span> o usuário <span class="fw-bold">@Model.Login</span>.
                </div>

            }
            else
            {
                <div class="modal-body enableDisableModal p-3">
                    <span class="text-danger fw-bold">Atenção!</span> habilitar o usuário fará com que ele retome o <span
                        class="fw-bold">completo acesso ao sistema</span>. Ao prosseguir você concorda em <span
                        class="fw-bold">habilitar</span> novamente o usuário <span class="fw-bold">@Model.Login</span>.
                </div>
            }

            <div class="modal-footer modal-footer-sm d-flex justify-content-start">
                <button type="button" title="cancelar ..." class="btn btn-sm btn-danger" data-bs-dismiss="modal"><i
                        class="bi bi-x-circle-fill"></i></button>
                <button type="button" title="confirmar ..." class="btn btn-sm btn-primary confirmAction"><i
                        class="bi bi-check-circle-fill"></i></button>
            </div>

        </div>

    </div>

</div>

@* Finish enable/disable user Modal *@

@* Início do Modal de Edição da senha do usuário *@

<div class="modal fade" id="adm-change-pass" tabindex="-1" role="dialog" aria-labelledby="change-admTitle"
    aria-hidden="true">

    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">

        <div class="modal-content">
            <div class="modal-header bg-light p-3">
                <h3 class="modal-title lead text-sm fw-bold mb-0 p-0" id="change-admTitle">Alterar senha</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-1">
                @await Html.PartialAsync("../ChangePassword/_ChangePass.cshtml", new ChangePassword())
            </div>
        </div>

    </div>

</div>

@* Fim do Modal de Edição da senha do usuário *@

Views/UserAdministrator/Index.cshtml
@using SEP_Web.ViewModels

@{
    ViewData["Title"] = "Administradores cadastrados";
}

<div>
    <div class="container-fluid justify-content-start w-100 pop-up">
        <a title="Cadastrar novo administrador ..." role="button" asp-controller="UserAdministrator"
            asp-action="Register" class="d-flex justify-content-evenly btn btn-md btn-primary"><i
                class="bi bi-person-plus-fill"></i> Novo</a>
         @await Html.PartialAsync("../Shared/Components/Alerts/_Alerts.cshtml")
    </div>

    <div class="card">
        <div class="card-header bg-primary text-light">
            <span class="fw-bold">Administradores :</span>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="administrator-table" class="table table-sm table-bordered table-striped table-light users-table">
                    <thead class="table-light border-light text-primary">
                        <tr>
                            <th scope="col">Status</th>
                            <th scope="col">MASP</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Login</th>
                            <th scope="col">E-mail</th>
                            <th scope="col">Telefone</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @* A tabela será preenchida pelo DataTables via AJAX *@
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="dynamic-modal"></div> @* Contêiner para injetar modais dinâmicos *@
</div>

Views/UserAdministrator/Register.cshtml
@model UserAdministrator

@using SEP_Web.Models
@using SEP_Web.Models.UsersModels
@using SEP_Web.Keys

@{
    ViewData["Title"] = "Cadastro de administrador";
}

<div class="container">

    <div class="row justify-content-center">

        <div class="col-md-8 p-0 m-0">

            <div class="d-flex justify-content-center align-items-center">
                <div class="adm-line"></div>
                <i style="font-size: 10vh; color: #0077cc;" class="bi bi-person-circle"></i>
                <div class="adm-line"></div>
            </div>

            <form class="register-adm-form" asp-controller="UserAdministrator" asp-action="Register" method="post">

                @await Html.PartialAsync("../Shared/Components/Alerts/_Alerts.cshtml")

                <div class="row">

                    <div class="col-md-6 adm-col">

                        <div class="form-group">

                            <label class="form-label" for="administrator-masp" hidden></label>
                            <input type="number" class="form-control" id="administrator-masp" name="masp" asp-for="Masp" placeholder="Nº do MASP" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Masp)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="administrator-name" hidden></label>
                            <input type="text" class="form-control" id="administrator-name" name="Name" asp-for="Name" placeholder="Nome completo" maxlength="50" minlength="10" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Name)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="administrator-login" hidden></label>
                            <input type="text" class="form-control" id="administrator-login" name="login" asp-for="Login" placeholder="Nome de login" maxlength="35" minlength="10" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Login)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="administrator-email" hidden></label>
                            <input type="text" class="form-control" id="administrator-email" name="email" asp-for="Email" placeholder="Informe seu e-mail" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Email)
                            </div>

                        </div>

                    </div>

                    <div class="col-md-6 adm-col">

                        <div class="form-group">

                            <label class="form-label" for="administrator-phone" hidden></label>
                            <input type="tel" class="form-control mask-phone" id="administrator-phone" name="phone" asp-for="Phone" maxlength="15" placeholder="(XX) XXXXX-XXXX" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Phone)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="administrator-position" hidden></label>
                            <input type="text" class="form-control" id="administrator-position" name="Position" asp-for="Position" placeholder="Seu cargo" maxlength="35" minlength="9" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Position)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="administrator-password" hidden></label>
                            <input type="password" class="form-control" id="administrator-password" name="password" asp-for="Password" placeholder="Informe uma senha" maxlength="100" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Password)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="administrator-confirmPass" hidden></label>
                            <input type="password" class="form-control" id="administrator-confirmPass" name="confirmPass" placeholder="Confirme sua senha" maxlength="100" autocomplete="disabled">
                            <div class="validate-fields">
                                <span class="field-validation-error">@TempData["ErrorPass"]</span>
                            </div>

                        </div>

                    </div>
                </div>

                <div class="form-group">
                    <button title="Cadastrar usuário ..." type="submit" class="btn btn-primary"><i class="bi bi-person-add" title="Cadastrar usuário ..."></i> Salvar</button>
                    <a href="/UserAdministrator/Index/" type="submit" class="btn btn-secondary" title="Cancelar cadastro ..."><i class="bi bi-arrow-return-left" title="Cancelar cadastro ..."></i></a>
                </div>

            </form>

        </div>

    </div>

</div>

Views/UserAdministrator/_Delete.cshtml
@model UsersViewModel

@using SEP_Web.ViewModels

@{
    ViewData["Title"] = "Excluir administrador";
}

<!-- Partial View de Exclusão de Usuário -->
<div>

    <form asp-controller="UserAdministrator" asp-action="Delete" method="post">

        <input type="hidden" asp-for="Id">

        <div class="p-2 text-justify">
            <span>Tem certeza que deseja excluir o(a) administrador(a) <b>@Model.Name</b>? Essa ação excluirá a conta e demais entidades <b>(Órgãos, Divisões, Seções e Setores)</b> relacionadas ao usuário de forma <b class="text-danger">permanente</b> e não poderá ser desfeita. Ao prosseguir você concorda com estes termos.</span>
        </div>

        <div class="modal-footer d-flex justify-content-start p-2">
            <button type="submit" class="btn btn-sm btn-danger" name="decision" type="submit" value="delete" title="Excluir - @Model.Login"><i class="bi bi-trash"></i></button>
            <a asp-controller="UserAdministrator" asp-action="Index" class="btn btn-sm btn-secondary" title="Cancelar"><i class="bi bi-arrow-return-left" title="Cancelar"></i></a>
        </div>

    </form>

</div>
<!-- / Partial View de Exclusão de Usuário -->