Models/UsersModels/CivilServant.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SEP_Web.Models.StructuresModels;

namespace SEP_Web.Models.UsersModels;

/// <summary>
///     <para><b>Servidores Públicos:</b></para>
///     <para>- Os servidores herdam seus atributos da classe base <b>SEP_Web.Models.Users</b> e também possuem atributos próprios.
///     Servidores são apenas um objeto de manipulação e possuem permissão de acesso apenas ao seu relatório de estágio.</para>
///     <para>- A classe <b>CivilServant</b> é usada para mapear uma tabela do banco de dados,
///     representando uma entidade gerada pelo <b>EF Core</b>.</para>
///     <para><b>Nome da Tabela:</b></para>
///     <para>- Servants;</para>
/// </summary>

[Table("Servants")]
public class CivilServant : Users
{
    [Required(ErrorMessage = "Informe a data de admissão !")]
    [DataType(DataType.DateTime)]
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
    public DateTime AdmissionDate { get; set; }

    [ForeignKey("InstituitionId"), Required(ErrorMessage = "Selecione um órgão !")]
    public int? InstituitionId { get; set; }
    public Instituition Instituition { get; set; }

    [ForeignKey("DivisionId"), Required(ErrorMessage = "Selecione uma divisão !")]
    public int? DivisionId { get; set; }
    public Division Division { get; set; }

    [ForeignKey("SectionId"), Required(ErrorMessage = "Selecione uma seção !")]
    public int? SectionId { get; set; }
    public Section Section { get; set; }

    [ForeignKey("SectorId"), Required(ErrorMessage = "Selecione um setor !")]
    public int? SectorId { get; set; }
    public Sector Sector { get; set; }

    [ForeignKey("UserEvaluatorFirst"), Required(ErrorMessage = "Informe o Avaliador 1 !")]
    public int? UserEvaluatorId1 { get; set; }
    public UserEvaluator UserEvaluatorFirst { get; set; }

    [ForeignKey("UserEvaluatorSecond"), Required(ErrorMessage = "Informe o Avaliador 2 !")]
    public int? UserEvaluatorId2 { get; set; }
    public UserEvaluator UserEvaluatorSecond { get; set; }
}

Controllers/Users/CivilServantController.cs
using Microsoft.AspNetCore.Mvc;
using MySqlConnector;
using SEP_Web.Filters;
using SEP_Web.Helper.Authentication;
using SEP_Web.Helper.Messages;
using SEP_Web.Helper.Validation;
using SEP_Web.Keys;
using SEP_Web.Models;
using SEP_Web.Models.UsersModels;
using SEP_Web.Models.AssessmentsModels;
using SEP_Web.Interfaces.UsersInterfaces;
using SEP_Web.Interfaces.AssessmentsInterfaces;
using SEP_Web.ViewModels;
using SEP_Web.Models.DataTableModels;

namespace SEP_Web.Controllers.UsersControllers;

[ServiceFilter(typeof(UserEvaluatorFilter))]
public class CivilServantController : Controller
{
    private readonly ILogger<CivilServantController> _logger;
    private readonly IUsersValidation _validation;
    private readonly IUserSession _session;
    private readonly ICivilServantServices _civilServantServices;
    private readonly IAssessmentServices _assessmentServices;

    public CivilServantController(ILogger<CivilServantController> logger, IUserSession session, IUsersValidation validation, ICivilServantServices civilServantServices, IAssessmentServices assessmentServices)
    {
        _logger = logger;
        _validation = validation;
        _session = session;
        _civilServantServices = civilServantServices;
        _assessmentServices = assessmentServices;
    }

    public IActionResult Index() => View();

    [HttpPost]
    public IActionResult Index(DataTableRequest request)
    {
        try
        {
            // Obter IQueryable<UserAdministrator> do serviço
            var query = _civilServantServices.ServantsAsQueryable();

            // Converter IQueryable<UserAdministrator> para IQueryable<UsersViewModel>
            var viewModels = ConvertToViewModel(query);

            // Aplicando a ordenação
            if (request.Order != null && request.Order.Any())
            {
                var columnIndex = request.Order[0].Column; // Índice da coluna que está sendo ordenada
                var sortDirection = request.Order[0].Dir; // Direção da ordenação: "asc" ou "desc"

                switch (columnIndex)
                {
                    case 0:
                        viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.UserStats).AsQueryable()  // Ajustar para a coluna correta
                            : viewModels.OrderByDescending(u => u.UserStats).AsQueryable();
                        break;
                    case 1:
                         viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.Masp).AsQueryable()
                            : viewModels.OrderByDescending(u => u.Masp).AsQueryable();
                        break;
                    case 2:
                        viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.Name).AsQueryable()
                            : viewModels.OrderByDescending(u => u.Name).AsQueryable();
                        break;
                    case 3:
                        viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.Login).AsQueryable()
                            : viewModels.OrderByDescending(u => u.Login).AsQueryable();
                        break;
                    case 4:
                        viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.Email).AsQueryable()
                            : viewModels.OrderByDescending(u => u.Email).AsQueryable();
                        break;
                    case 5:
                        viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.Phone).AsQueryable()
                            : viewModels.OrderByDescending(u => u.Phone).AsQueryable();
                        break;
                    default:
                        break;
                }
            }

            // Filtragem para busca via search
            if (!string.IsNullOrEmpty(request.Search.Value))
            {
                string searchValue = request.Search.Value.ToLower();
                viewModels = viewModels.Where(vm =>
                    vm.Name.ToLower().Contains(searchValue) ||
                    vm.Login.ToLower().Contains(searchValue) ||
                    vm.Email.ToLower().Contains(searchValue) ||
                    vm.Phone.ToLower().Contains(searchValue)
                ).AsQueryable();
            }

            // Filtragem, paginação e ordenação pelo DataTables
            var filteredData = viewModels.Skip(request.Start).Take(request.Length).ToList();
            var response = new
            {
                draw = request.Draw,
                recordsTotal = viewModels.Count(),
                recordsFiltered = viewModels.Count(),
                data = filteredData
            };

            return Json(response);
        }
        catch (MySqlException ex)
        {
            // MYSQL EXEPTIONS :

            _logger.LogError("{exceptionMessage} : {Message}, ErrorCode = {errorCode} - Represents {Error} ", ExceptionMessages.ErrorDatabaseConnection, ex.Message.ToUpper(), ex.Number, ex.ErrorCode);
            return new JsonResult(new
            {
                draw = 0,
                recordsTotal = 0,
                recordsFiltered = 0,
                data = new List<UsersViewModel>()
            });
        }
        catch (ArgumentNullException ex2)
        {
            // NULL EXEPTIONS :

            _logger.LogWarning("{exceptionMessage} : {Message} value = '{InnerExeption}'", FeedbackMessages.ErrorEmptyCollection, ex2.Message, ex2.InnerException);
            return new JsonResult(new
            {
                draw = 0,
                recordsTotal = 0,
                recordsFiltered = 0,
                data = new List<UsersViewModel>()
            });
        }
    }

    public IActionResult Register() => View();

    [HttpPost]
    public async Task<IActionResult> Register(CivilServant servant, Assessment assessment, string confirmPass)
    {

        try
        {

            if (string.IsNullOrEmpty(confirmPass))
            {
                TempData["ErrorPass"] = FeedbackMessages.ConfirmPassword;
                return View(servant);
            }

            if (ModelState.IsValid)
            {
                List<(string FieldName, string Message)> duplicateErrors = await _validation.CheckForDuplicateUserFields(servant);

                foreach (var (FieldName, Message) in duplicateErrors)
                    ModelState.AddModelError(FieldName, Message);

                if (ModelState.ErrorCount > 0)
                    return View(servant);

                if (!_validation.ValidatePassword(servant.Password, confirmPass, this))
                    return View(servant);

                TempData["SuccessMessage"] = FeedbackMessages.SuccessServantRegister;

                await _civilServantServices.RegisterServant(servant);
                await _assessmentServices.RegisterAssessments(assessment, servant);

                return RedirectToAction("Index");
            }

            return View(servant);
        }
        catch (MySqlException ex)
        {
            TempData["ErrorMessage"] = $"{FeedbackMessages.ErrorServantRegister} {ExceptionMessages.ErrorDatabaseConnection}";

            _logger.LogError("{exceptionMessage} : {Message}, ErrorCode = {errorCode} - Represents {Error} ", ExceptionMessages.ErrorDatabaseConnection, ex.Message.ToUpper(), ex.Number, ex.ErrorCode);

            _logger.LogError("{exceptionMessage} : {Description} - ", ExceptionMessages.ErrorUnexpected, ex.StackTrace.Trim());

            servant = null;
            return View(servant);
        }
        catch (Exception ex2)
        {
            TempData["ErrorMessage"] = FeedbackMessages.ErrorServantRegister;

            _logger.LogWarning("{exceptionMessage} : {Message} value = '{InnerExeption}'", ExceptionMessages.ErrorUnexpected, ex2.Message, ex2.InnerException);

            _logger.LogWarning("{exceptionMessage} : {Description}", ExceptionMessages.ErrorUnexpected, ex2.StackTrace.Trim());

            servant = null;
            return View(servant);
        }
    }

    public IActionResult Edit(int id) => View(_civilServantServices.SearchForId(id));

    [HttpPost]
    public async Task<IActionResult> Edit(ModifyUser modifyUser)
    {
        try
        {
            CivilServant userEdit = _civilServantServices.SearchForId(modifyUser.Id);

            if (ModelState.IsValid)
            {
                Users userInSession = await _session.SearchUserSession();

                bool enableAccount = Request.Form["enableDisableAccount"] == "on";

                if (enableAccount)
                {
                    userEdit.UserStats = userEdit.UserStats == UserStatsEnum.Active ? UserStatsEnum.Inactive : UserStatsEnum.Active;
                }

                var fieldsToValidate = new List<(string FieldName, object Value)>
                {
                    ("Masp", modifyUser.Masp),
                    ("Name", modifyUser.Name),
                    ("Login", modifyUser.Login),
                    ("Email", modifyUser.Email),
                    ("Phone", modifyUser.Phone),
                };

                foreach (var (fieldName, value) in fieldsToValidate)
                    if (_validation.IsFieldChanged(userEdit, fieldName, value))
                        if (await _validation.CheckIfFieldExistsInAnyUserTable(fieldName, value))
                            ModelState.AddModelError(fieldName, $"O {fieldName.ToLower()} informado já está em uso.");

                if (ModelState.ErrorCount > 0)
                    return View(userEdit);


Views/CivilServant/Index.cshtml
@using SEP_Web.ViewModels

@inject IHttpContextAccessor _httpContext

@{
    ViewData["Title"] = "Servidores cadastrados";
}

<div>
    <div class="container-fluid justify-content-start w-100 pop-up">
        <a title="Cadastrar novo servidor ..." role="button" asp-controller="CivilServant" asp-action="Register"
            class="d-flex justify-content-evenly btn btn-md btn-primary"><i class="bi bi-person-plus-fill"></i> Novo</a>
        @await Html.PartialAsync("../Shared/Components/Alerts/_Alerts.cshtml")
    </div>

    <div class="card">
        <div class="card-header bg-primary text-light">
            <span class="fw-bold">Servidores :</span>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="servant-table"
                    class="table table-sm table-bordered table-striped table-light users-table p-0">
                    <thead class="table-light border-light text-primary">
                        <tr>
                            <th scope="col">Status</th>
                            <th scope="col">MASP</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Login</th>
                            <th scope="col">E-mail</th>
                            <th scope="col">Telefone</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @* A tabela será preenchida pelo DataTables via AJAX *@
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="dynamic-modal"></div> @* Contêiner para injetar modais dinâmicos *@
</div>

<script type="text/javascript">
    var currentUserType = '@_httpContext.HttpContext.Session.GetInt32("userType")';
</script>

Views/CivilServant/Register.cshtml
@model CivilServant

@using SEP_Web.Models.UsersModels
@using SEP_Web.Interfaces.StructuresInterfaces
@using SEP_Web.Keys

@inject IInstituitionServices _instituitionServices

@{
    ViewData["Title"] = "Cadastro de servidores";
}

<div class="container">

    <div class="row justify-content-center">

        <div class="col-md-8 p-0 m-0">

            <div class="d-flex justify-content-center align-items-center">
                <div class="eval-line"></div>
                <i style="font-size: 10vh; color: #0077cc;" class="bi bi-person-video2"></i>
                <div class="eval-line"></div>
            </div>

            <form class="servant-register register-adm-form justify-content-center" asp-controller="CivilServant" asp-action="Register" method="post">

                @await Html.PartialAsync("../Shared/Components/Alerts/_Alerts.cshtml")

                <div class="row">

                    <div class="col-md-6 adm-col">

                        <div class="form-group">

                            <label class="form-label" for="servant-masp" hidden></label>
                            <input type="number" class="form-control" id="servant-masp" name="Masp" asp-for="Masp" placeholder="Nº do MASP" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Masp)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="servant-name" hidden></label>
                            <input type="text" class="form-control" id="servant-name" name="Name" asp-for="Name" placeholder="Nome completo" maxlength="50" minlength="10" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Name)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="servant-login" hidden></label>
                            <input type="text" class="form-control" id="servant-login" name="Login" asp-for="Login" placeholder="Nome de login" maxlength="50" minlength="10" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Login)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="servant-email" hidden></label>
                            <input type="text" class="form-control" id="servant-email" name="Email" asp-for="Email" placeholder="Informe seu e-mail" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Email)
                            </div>

                        </div>

                    </div>

                    <div class="col-md-6">

                        <div class="form-group">

                            <label class="form-label" for="servant-phone" hidden></label>
                            <input type="tel" class="form-control mask-phone" id="servant-phone" name="phone" asp-for="Phone" maxlength="15" placeholder="(XX) XXXXX-XXXX" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Phone)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="servant-position" hidden></label>
                            <input type="text" class="form-control" id="servant-position" name="Position" asp-for="Position" placeholder="Seu cargo" maxlength="35" minlength="5" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Position)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="servant-password" hidden></label>
                            <input type="password" class="form-control" id="servant-password" name="Password" asp-for="Password" placeholder="Informe uma senha" maxlength="100" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.Password)
                            </div>

                        </div>

                        <div class="form-group">

                            <label class="form-label" for="servant-confirmPass" hidden></label>
                            <input type="password" class="form-control" id="servant-confirmPass" name="confirmPass" placeholder="Confirme sua senha" maxlength="100" autocomplete="disabled">
                            <div class="validate-fields">
                                <span class="field-validation-error">@TempData["ErrorPass"]</span>
                            </div>

                        </div>

                    </div>

                </div>
                    <hr class="m-0">
                <div class="row">
                    <div class="col-md-6 adm-col">

                        <div class="form-group">
                            <select class="servant-instituition form-select" name="instituitionId" asp-for="InstituitionId">

                                @foreach (var i in await _instituitionServices.InstituitionsList())
                                {
                                    <option value="@i.Id">@i.Name</option>
                                }
                            </select>
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.InstituitionId)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.DropDownListFor(model => model.DivisionId, Enumerable.Empty<SelectListItem>(), "-- selecione a divisão --", new { @class = "servant-division form-select w-100" })
                                <div class="validate-fields">
                                    @Html.ValidationMessageFor(x => x.DivisionId)
                                </div>
                        </div>

                        <div class="form-group">
                            @Html.DropDownListFor(model => model.SectionId, Enumerable.Empty<SelectListItem>(), "-- selecione a seção --", new { @class = "servant-section form-select w-100" })
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.SectionId)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.DropDownListFor(model => model.SectorId, Enumerable.Empty<SelectListItem>(), "-- selecione o setor --", new { @class = "servant-sector form-select w-100" })
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.SectorId)
                            </div>
                        </div>

                    </div>

                    <div class="col-md-6">

                        <div class="form-group">
                            @Html.DropDownListFor(model => model.UserEvaluatorId1, Enumerable.Empty<SelectListItem>(), "-- selecione o avaliador 1 --", new { @class = "servant-evaluator-first form-select w-100" })
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.UserEvaluatorId1)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.DropDownListFor(model => model.UserEvaluatorId2, Enumerable.Empty<SelectListItem>(), "-- selecione o avaliador 2 --", new { @class = "servant-evaluator-second form-select w-100" })
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.UserEvaluatorId2)
                            </div>
                        </div>

                        <div class="form-group">

                            <label class="form-label" for="servant-admission" hidden></label>
                            <input type="date" class="form-control" id="servant-admission" asp-for="AdmissionDate" title="Data de admissão" data-bs-toggle="tooltip" data-bs-placement="bottom" autocomplete="disabled">
                            <div class="validate-fields">
                                @Html.ValidationMessageFor(x => x.AdmissionDate)
                            </div>

                        </div>

                    </div>
                </div>

                <div class="form-group">
                    <button title="Cadastrar usuário ..." type="submit" class="btn btn-primary"><i class="bi bi-person-add" title="Cadastrar usuário ..."></i> Salvar</button>
                    <a href="/CivilServant/Index/" type="submit" class="btn btn-secondary" title="Cancelar cadastro ..."><i class="bi bi-arrow-return-left" title="Cancelar cadastro ..."></i></a>
                </div>

            </form>

        </div>

    </div>

</div>

Views/CivilServant/_Delete.cshtml
@model UsersViewModel

@using SEP_Web.ViewModels

@{
    ViewData["Title"] = "Excluir Servidor";
}

<!-- Partial View de Exclusão de Usuário -->
<div>

    <form asp-controller="CivilServant" asp-action="Delete" method="post">

        <input type="hidden" asp-for="Id">

        <div class="p-2 text-justify">
            <span>Tem certeza que deseja excluir o(a) servidor(a) <b>@Model.Name</b>? Essa ação excluirá <b>todas as avaliações</b> deste usuário de forma <b class="text-danger">permanente</b> e não poderá ser desfeita.</span>
        </div>

        <div class="modal-footer d-flex justify-content-start p-2">
            <button type="submit" class="btn btn-sm btn-danger" name="decision" type="submit" value="delete" title="Excluir - @Model.Login"><i class="bi bi-trash"></i></button>

            <a asp-controller="CivilServant" asp-action="Index" class="btn btn-sm btn-secondary" title="Cancelar"><i class="bi bi-arrow-return-left" title="Cancelar"></i></a>
        </div>

    </form>

</div>
<!-- / Partial View de Exclusão de Usuário -->

Views/CivilServant/_DeleteModal.cshtml
@model UsersViewModel

@using SEP_Web.ViewModels

@* Start Delete Modal *@
<div class="modal fade" id="deleteServant@(Model.Id)" tabindex="-1" role="dialog"
    aria-labelledby="deleteServant@(Model.Id)" aria-hidden="true">
    <div class="modal-dialog modal-md modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger text-light p-3">
                <h3 class="modal-title text-center fs-4 mb-0 p-0" id="deleteTitle">
                    Alerta</h3>
                <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body p-1">
                @await Html.PartialAsync("_Delete.cshtml", Model)
            </div>
        </div>
    </div>
</div>