Models/StructuresModels/Instituition.cs
#nullable enable

using System.ComponentModel.DataAnnotations.Schema;

namespace SEP_Web.Models.StructuresModels;

[Table("Instituitions")]
public class Instituition : Structures
{

}

ViewModels/InstituitionViewModel.cs
namespace SEP_Web.ViewModels;
public class InstituitionViewModel
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int UserAdministratorId { get; set; }
}

Controllers/Structures/InstituitionController.cs
using Microsoft.AspNetCore.Mvc;
using SEP_Web.Helper.Authentication;
using SEP_Web.Filters;
using SEP_Web.Models.StructuresModels;
using SEP_Web.Models.UsersModels;
using SEP_Web.Interfaces.StructuresInterfaces;
using MySqlConnector;
using SEP_Web.Helper.Messages;
using System.Reflection;
using SEP_Web.ViewModels;
using SEP_Web.Models.DataTableModels;

namespace SEP_Web.Controllers.StructuresController;

[ServiceFilter(typeof(UserAdminFilter))]
public class InstituitionController : Controller
{
    private readonly ILogger<InstituitionController> _logger;
    private readonly IInstituitionServices _instituitionServices;
    private readonly IUserSession _session;

    public InstituitionController(ILogger<InstituitionController> logger, IInstituitionServices instituitionServices, IUserSession session)
    {
        _logger = logger;
        _instituitionServices = instituitionServices;
        _session = session;
    }

    public IActionResult Index() => View();

    [HttpPost]
    public IActionResult Index(DataTableRequest request)
    {
        try
        {
            // Obter IQueryable<Instituition> do serviço
            var query = _instituitionServices.InstituitionsAsQueryable();

            // Converter IQueryable<Instituition> para IQueryable<InstituitionViewModel>
            var viewModels = ConvertToViewModel(query);

            // Aplicando a ordenação
            if (request.Order != null && request.Order.Any())
            {
                var columnIndex = request.Order[0].Column; // Índice da coluna que está sendo ordenada
                var sortDirection = request.Order[0].Dir; // Direção da ordenação: "asc" ou "desc"

                switch (columnIndex)
                {
                    case 0:
                        viewModels = sortDirection == "asc"
                            ? viewModels.OrderBy(u => u.Name).AsQueryable()
                            : viewModels.OrderByDescending(u => u.Name).AsQueryable();
                        break;
                    default:
                        break;
                }
            }

            // Aplicar filtros de pesquisa, se houver
            if (!string.IsNullOrEmpty(request.Search?.Value))
            {
                var searchValue = request.Search.Value.ToLower();
                viewModels = viewModels.Where(s => s.Name.ToLower().Contains(searchValue));
            }

            // Filtragem, paginação e ordenação pelo DataTables
            var filteredData = viewModels.Skip(request.Start).Take(request.Length).ToList();
            var response = new
            {
                draw = request.Draw,
                recordsTotal = viewModels.Count(),
                recordsFiltered = viewModels.Count(),
                data = filteredData
            };

            return Json(response);
        }
        catch (MySqlException dbException)
        {
            // MYSQL EXEPTIONS :

            _logger.LogError("{exceptionMessage} : {Message}, ErrorCode = {errorCode} - Represents {Error} ", ExceptionMessages.ErrorDatabaseConnection, dbException.Message.ToUpper(), dbException.Number, dbException.ErrorCode);

            return new JsonResult(new
            {
                draw = 0,
                recordsTotal = 0,
                recordsFiltered = 0,
                data = new List<InstituitionViewModel>()
            });
        }
        catch (ArgumentNullException ex)
        {
            // NULL EXEPTIONS :

            _logger.LogWarning("{exceptionMessage} : {Message} value = '{InnerExeption}'", ExceptionMessages.ErrorArgumentNullException, ex.Message, ex.InnerException);

            return new JsonResult(new
            {
                draw = 0,
                recordsTotal = 0,
                recordsFiltered = 0,
                data = new List<InstituitionViewModel>()
            });
        }
        catch (TargetParameterCountException ex2)
        {
            // EMPTY EXEPTIONS :

            _logger.LogWarning("{exceptionMessage} : {Message} value = '{InnerExeption}'", FeedbackMessages.ErrorEmptyCollection, ex2.Message, ex2.InnerException);

            return new JsonResult(new
            {
                draw = 0,
                recordsTotal = 0,
                recordsFiltered = 0,
                data = new List<InstituitionViewModel>()
            });
        }
    }

    [HttpPost]
    public async Task<IActionResult> Register(Instituition instituition)
    {
        try
        {
            if (ModelState.IsValid)
            {
                Users userInSession = await _session.SearchUserSession();
                instituition.UserAdministratorId = userInSession.Id;

                await _instituitionServices.RegisterInstituition(instituition);
                TempData["SuccessMessage"] = "Órgão cadastrado com sucesso.";
                return Json(new { stats = "OK" });
            }

            return Json(new { stats = "ERROR", message = "Não foi possível cadsatrar o órgão!" });
        }
        catch (Exception e)
        {
            _logger.LogError("Não foi possível cadsatrar o órgão. Error : {Message}", e.Message);
            return Json(new { stats = "INVALID", message = "Não foi possível cadsatrar o órgão!" });
        }
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Instituition instituition)
    {
        try
        {
            if (ModelState.IsValid)
            {
                Users userInSession = await _session.SearchUserSession();

                instituition.UserAdministratorId = userInSession.Id;
                instituition.LastModifiedBy = userInSession.Login;

                await _instituitionServices.InstituitionEdit(instituition);
                TempData["SuccessMessage"] = "órgão editado com sucesso.";
                return Json(new { stats = "OK" });
            }

            return Json(new { stats = "ERROR" });
        }
        catch (Exception e)
        {
            TempData["ErrorMessage"] = "Não foi possível editar o órgão.";
            _logger.LogError("Não foi possível editar o órgão. Error : {Message}", e.Message);
            return Json(new { stats = "INVALID", message = "Não foi possível editar o órgão!" });
        }
    }

    [HttpPost]
    public IActionResult Delete(string decision, Instituition instituition)
    {

        try
        {
            if (decision == "delete")
            {
                if (instituition.Id != 0)
                {
                    _instituitionServices.DeleteInstituition(instituition.Id);
                    TempData["SuccessMessage"] = "Órgão excluído com sucesso.";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["ErrorMessage"] = "Não foi possível excluir o órgão.";
            }

            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            TempData["ErrorMessage"] = "Não foi possível excluir o órgão.";
            _logger.LogError("Não foi possível excluir o órgão. Error : {Message}", e.Message);
            return RedirectToAction("Index");
        }

    }

    private static IQueryable<InstituitionViewModel> ConvertToViewModel(IQueryable<Instituition> instituitions)
    {
        return instituitions.Select(x => new InstituitionViewModel
        {
            Id = x.Id,
            Name = x.Name
        });
    }

    public async Task<IActionResult> EditModal(int id)
    {
        var section = await _instituitionServices.GetByIdAsync(id);
        return PartialView("_EditModal", section);
    }

    public async Task<IActionResult> DeleteModal(int id)
    {
        var section = await _instituitionServices.GetByIdAsync(id);
        return PartialView("_DeleteModal", section);
    }
}

Views/Instituition/Index.cshtml
@using SEP_Web.Models.StructuresModels

@{
    ViewData["Title"] = "Órgãos";
}

<div>
    <div class="container-fluid justify-content-start w-100 pop-up">
        <a title="Cadastrar novo órgão ..." type="button" data-bs-toggle="modal" data-bs-target="#instituition-register"
            class="btn btn-primary d-flex justify-content-evenly btn-md"><i class="bi bi-building-add"></i> Novo</a>
        @await Html.PartialAsync("../Shared/Components/Alerts/_Alerts.cshtml")
    </div>

    @* Modal de Registro *@
    <div class="modal fade" id="instituition-register" tabindex="-1" role="dialog"
        aria-labelledby="instituition-registerTitle" aria-hidden="true">
        <div class="modal-dialog modal-md modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header bg-primary text-light p-3">
                    <h3 class="modal-title fs-4 text-center">Adicionar órgão</h3>
                    <a type="button" class="btn-close bg-light" asp-action="Index" asp-controller="Instituition"></a>
                </div>
                <div class="modal-body p-1">
                    @await Html.PartialAsync("_Register.cshtml", new Instituition())
                </div>
            </div>
        </div>
    </div>
    @* Fim do Modal de Registro *@

    <div class="card">
        <div class="card-header bg-primary text-light">
            <span class="fw-bold">@ViewData["Title"] :</span>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="instituition-table"
                    class="table table-sm table-bordered table-striped table-light duo-table p-0">
                    <thead class="table-light border-light text-primary">
                        <tr>
                            <th scope="col">Descrição</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @* A tabela será preenchida pelo DataTables via AJAX *@
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="dynamic-modal"></div> @* Contêiner para injetar modais dinâmicos *@
</div>

Views/Instituition/_Delete.cshtml
@model InstituitionViewModel

@using SEP_Web.Models.StructuresModels
@using SEP_Web.ViewModels

@{
    ViewData["Title"] = "Excluir Usuário";
}

<!-- Partial View de Exclusão de Órgãos -->

<div>

    <form asp-controller="Instituition" asp-action="Delete" method="post">

        <input type="hidden" asp-for="Id">

        <div class="p-3">
            <span>Tem certeza que deseja excluir o órgão: <b>@Model.Name</b>? Essa ação irá excluí-lo de forma <b class="text-danger">permanente</b>, consequentemente todas as demais entidades
             <b>(Divisões, Seções, Setores, Avaliadores e Servidores)</b> que foram cadastradas com base neste órgão serão excluídas. A ação não poderá ser desfeita, ao prosseguir você concorda com estes termos.</span>
        </div>

        <div class="modal-footer -flex justify-content-start p-2">
            <button type="submit" class="btn btn-danger btn-sm" name="decision" value="delete" title="Excluir órgão ..."><i title="Excluir órgão ..." class="bi bi-trash"></i></button>
            <a asp-controller="Instituition" asp-action="Index" class="btn btn-secondary btn-sm" title="Cancelar"><i class="bi bi-arrow-return-left" title="Cancelar"></i></a>
        </div>

    </form>

</div>

<!-- / Partial View de Exclusão de Órgãos -->

Views/Instituition/_DeleteModal.cshtml
@model InstituitionViewModel

@using SEP_Web.ViewModels

@* Modal de Exclusão *@
<div class="modal fade" id="deleteInstituition@(Model.Id)" tabindex="-1" role="dialog"
    aria-labelledby="deleteInstituition@(Model.Id)" aria-hidden="true">
    <div class="modal-dialog modal-md modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger p-3">
                <h3 class="modal-title text-light fs-4 text-center">Alerta</h3>
                <a type="button" class="btn-close bg-light" asp-action="Index" asp-controller="Instituition"></a>
            </div>
            <div class="modal-body p-1">
                @await Html.PartialAsync("_Delete.cshtml", Model)
            </div>
        </div>
    </div>
</div>

Views/Instituition/_Edit.cshtml
@model InstituitionViewModel

@using SEP_Web.Models.StructuresModels
@using SEP_Web.ViewModels

@{
    ViewData["Title"] = "Edição de órgão";
}

<!-- Partial View de Edição de Órgãos -->

<div>

    <form id="edit-instiuition-form" asp-action="Edit" asp-controller="Instituition" method="post">

        <input id="edit-instituition-id" type="hidden" asp-for="Id">

        <div class="form-group p-4">
            <label class="form-label" for="edit-instituition-name" hidden>Nome do órgão: </label>
            <input type="text" placeholder="Informe a descrição do órgão :" class="form-control" maxlength="70" minlength="10" id="edit-instituition-name"
                asp-for="Name" autocomplete="disabled"/>
            <div class="validate-fields">
                <span class="field-validation-error"></span>
            </div>
        </div>

        <div class="d-flex justify-content-start modal-footer p-2">
            <button type="submit" class="btn btn-sm btn-primary btn-save" title="Editar ..."><i class="bi bi-check-circle-fill" title="Cadastrar ..."></i></button>
            <a asp-controller="Instituition" asp-action="Index" class="btn btn-sm btn-danger" title="Cancelar ..."><i class="bi bi-x-circle-fill" title="Cancelar ..."></i></a>
        </div>

    </form>

</div>

<!-- Partial View de Edição de Órgãos -->

Views/Instituition/_EditModal.cshtml
@model InstituitionViewModel

@using SEP_Web.ViewModels

@* Modal de Edição *@
<div class="modal fade" id="edit-instituitionModal@(Model.Id)" tabindex="-1" role="dialog"
    aria-labelledby="edit-instituitionModal@(Model.Id)" aria-hidden="true">
    <div class="modal-dialog modal-md modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary p-3">
                <h3 class="modal-title text-light fs-4 text-center">Editar órgão</h3>
                <a type="button" class="btn-close bg-light" asp-action="Index" asp-controller="Instituition"></a>
            </div>
            <div class="modal-body p-1">
                @await Html.PartialAsync("_Edit.cshtml", Model)
            </div>
        </div>
    </div>
</div>

Views/Instituition/_Register.cshtml
@model Instituition

@using SEP_Web.Models
@using SEP_Web.Models.StructuresModels

@{
    ViewData["Title"] = "Cadastrar Órgão";
}

<!-- Partial View de Cadastro de Órgãos -->

<div>

    <form id="instituition-form">

        <div class="form-group p-4">
            <label class="form-label" for="instituition-name" hidden></label>
            <input type="text" placeholder="Informe a descrição do órgão :" class="form-control" id="instituition-name" name="name" autocomplete="disabled"/>
            <div class="validate-fields">
                <span class="field-validation-error"></span>
            </div>
        </div>

        <div class="d-flex justify-content-start modal-footer p-2">

            <button type="submit" class="btn btn-sm btn-primary" title="Cadastrar ..."><i class="bi bi-check-circle-fill" title="Cadastrar ..."></i></button>
            <a href="/Instituition/Index/" class="btn btn-sm btn-danger" title="Cancelar ..."><i class="bi bi-x-circle-fill" title="Cancelar ..."></i></a>

        </div>

    </form>

</div>

<!-- Partial View de Cadastro de Órgãos -->